spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ems
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    thymeleaf:
    cache: false
  jpa:
    hibernate.ddl-auto: update
  application:
    name: EMS-app
server:
  port: 8080





